export default {
  NOTIFICATION_READED: 'NOTIFICATION_READED',
  ALL_READED: 'ALL_READED',
  START_READ: 'START_READ',
  END_READ: 'END_READ',
  PULL_NOTIFICATION_LIST: 'PULL_NOTIFICATION_LIST',
  START_LOGIN: 'START_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
}